# Dockerfile.nginx
FROM nginx:1.27-alpine

# Copy Nginx configuration
COPY docker/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

# Set working directory
WORKDIR /var/www/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]