version: '3.8'

services:
  k6:
    image: loadimpact/k6:latest
    container_name: k6
    volumes:
      - .:/scripts
    environment:
      - API_URL=http://host.docker.internal:8000
    command: ["run", "-o", "json=./results.json", "/scripts/k6/loadtest.js"]